name: Deploy Staging Env

on:
  push:
    branches:
      - master

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke deployment hook
        uses: distributhor/workflow-webhook@v3
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
