name: Label Pull Request

on:
  pull_request:
    types: [ opened ]

permissions:
  contents: read

jobs:
  pr_labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
      - uses: TimonVS/pr-labeler-action@v5
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN }}

  pr_updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour obtenir tous les commits

      - name: Update PR Title and Description
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMITS=$(gh pr view $PR_NUMBER --json commits --jq '.commits[].messageBody')
          TITLE=$(gh pr view $PR_NUMBER --json commits --jq '.commits[].messageHeadline' | tail -1)
          TITLE=${TITLE:0:256}
          DESCRIPTION=$(gh pr view $PR_NUMBER --json commits --jq '.commits[].messageBody')

          if [ -n "$TITLE" ]; then
            gh pr edit $PR_NUMBER --title "$TITLE" --body "$DESCRIPTION"
          else
            echo "Le titre est vide, la mise à jour du PR est annulée."
          fi
