name: UpdatePR
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  update-pr:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      URL_BASE: http://${{ secrets.URL_OLLAMA_SERVER }}:11434/api/generate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Nécessaire pour obtenir tous les commits

      - name: Count Commits
        id: count
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMITS=$(gh pr view $PR_NUMBER --json commits --jq '.commits | length')
          echo "::set-output name=count::$COMMITS"

      - name: Generate PR title from commits
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          COMMITS=$(gh pr view $PR_NUMBER --json commits --jq '.commits[].messageBody')

          TITLE_REVIEW=$(curl -s -H "Content-Type: application/json" -d "{ \"model\":\"llama3\", \
          \"prompt\":\"Generate a PR title from these commits:\n$COMMITS\", \"stream\":false}" "$URL_BASE" | jq -r '.response')

          if [ -n "$TITLE_REVIEW" ]; then
            gh pr edit $PR_NUMBER --title "$TITLE_REVIEW"
          else
            echo "Title is empty, cannot update PR."
          fi
        if: steps.count.output.count > 1

      - uses: octue/generate-pull-request-description@1.0.0.beta-2
        id: pr-description
        with:
          pull_request_url: ${{ github.event.pull_request.url }}
          api_token: ${{ secrets.ACCESS_TOKEN }}

      - name: Update pull request body
        uses: riskledger/update-pr-description@v2
        with:
          body: ${{ steps.pr-description.outputs.pull_request_description }}
          token: ${{ secrets.ACCESS_TOKEN }}
